#!/usr/bin/env bash
# A script to display listening ports (TCP/UDP)

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root to display all listening ports"
    exit 1
fi

echo "Active Internet connections (only servers)"
netstat -tulnp | grep LISTEN

echo "Active UNIX domain sockets (only servers)"
netstat -lxp
